#!/bin/bash
xclip -out -selection clipboard > /tmp/old_clipboard
source ~/.config/rclipboard/rclipboard_file_path
cat $path | xclip -selection clipboard
sleep 0.3
if [ "$1" = "shift" ]; then
    xdotool key ctrl+shift+v
else
    xdotool key ctrl+v
fi
cat /tmp/old_clipboard | xclip -selection clipboard
rm /tmp/old_clipboard


